import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('iris')
print("Shape of dataset", df.shape)
print("\n Column names:-", df.columns.to_list())
print("\n First five rows:-",df.head())
print("\n Dataset info:-", df.info())
print("\n Summary Statistics :-",df.describe())
plt.figure()
sns.scatterplot(x='sepal_length',y='petal_length',hue='species',data=df)
plt.title("Sepal length vs Petal length")
plt.show()
df.hist(figsize=(8,6))
plt.suptitle("Features Distribution")
plt.show()
plt.figure()
sns.boxplot(data=df)
plt.title("Box plot for Iris Features")
plt.show()
